import "./globals.css";
import type { Metadata } from "next";
import Providers from "../../components/providers";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Mani Alipour",
  icons: "/images/profile-photo.png",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { locale } = await params;
  const isFa = locale === "fa";
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      dir={isFa ? "rtl" : "ltr"}
      className={isFa ? "font-vazir" : "font-ubuntu"}
    >
      <body className="overflow-x-hidden max-w-screen mx-auto">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
