import "./globals.css";
import type { Metadata } from "next";
import Providers from "../../components/providers";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const isFa = params.locale === "fa";
  const messages = await getMessages();

  return (
    <html
      lang={params.locale}
      dir={isFa ? "rtl" : "ltr"}
      className={isFa ? "font-vazir" : "font-ubuntu"}
    >
      <body className="overflow-x-hidden max-w-screen mx-auto">
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
